on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase/liquibase-github-action@v5
        with:
          operation: 'update'
          classpath: 'example/changelogs:example/changelogs/mysql-connector-java-8.0.29.jar'
          changeLogFile: 'myliquibase.mysql.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}